apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet8-template
  title: Dotnet 8 Template
  description: Scaffold a new .NET 8 project
  tags:
    - dotnet
    - csharp
    - webapi

spec:
  owner: user:mmatallanar-ua
  type: service

  parameters:
    - title: Complete the form to create a new .NET 8 project
      required:
        - name
        - description
        - owner
      properties:

        name:
          type: string
          title: Project Name
          description: The name of the project
          ui:autofocus: true

        description:
          title: Description
          type: string

        owner:
          title: Owner
          type: string
          ui:field: OwnerPicker

        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: System

    - title: Choose a destination
      required:
        - repoUrl
      properties:

        repoUrl:
          title: Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - mmatallanar-ua

  steps:

    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          repoUrl: ${{ parameters.repoUrl }}
          system: ${{ parameters.system }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        gitCommitMessage: Initial commit from Backstage template
        topics:
          - backstage
          - dotnet
          - webapi

    - id: dispatch-ci
      name: Start GitHub Action
      action: github:actions:dispatch
      input:
        workflowId: ci.yml
        repoUrl: ${{ parameters.repoUrl }}
        branchOrTagName: main

    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:

      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
